"""initial_schema

Revision ID: 712caca27763
Revises: 
Create Date: 2026-07-25 17:43:29.661065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '712caca27763'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('canonical_entities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('canonical_label', sa.String(length=512), nullable=False),
    sa.Column('entity_type', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('global_eligible', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('topics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('topic_key', sa.String(length=128), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('scope_json', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('topic_key')
    )
    op.create_table('canonical_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('topic_id', sa.UUID(), nullable=False),
    sa.Column('display_title', sa.String(length=512), nullable=False),
    sa.Column('event_type', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('graph_relationships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('topic_id', sa.UUID(), nullable=False),
    sa.Column('subject_type', sa.String(length=32), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('object_type', sa.String(length=32), nullable=False),
    sa.Column('object_id', sa.UUID(), nullable=False),
    sa.Column('relationship_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('temporal_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('raw_packages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('package_id', sa.UUID(), nullable=False),
    sa.Column('schema_version', sa.String(length=16), nullable=False),
    sa.Column('topic_id', sa.UUID(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('payload_bytes', sa.LargeBinary(), nullable=False),
    sa.Column('payload_checksum', sa.String(length=64), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('claim_mentions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('raw_package_id', sa.UUID(), nullable=False),
    sa.Column('local_id', sa.String(length=128), nullable=False),
    sa.Column('original_text', sa.String(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['raw_package_id'], ['raw_packages.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('raw_package_id', 'local_id')
    )
    op.create_table('claims',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('topic_id', sa.UUID(), nullable=False),
    sa.Column('original_text', sa.String(), nullable=False),
    sa.Column('epistemic_status', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('canonical_event_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['canonical_event_id'], ['canonical_events.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entity_mentions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('raw_package_id', sa.UUID(), nullable=False),
    sa.Column('local_id', sa.String(length=128), nullable=False),
    sa.Column('label', sa.String(length=512), nullable=False),
    sa.Column('source_type', sa.String(length=128), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['raw_package_id'], ['raw_packages.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('raw_package_id', 'local_id')
    )
    op.create_table('event_mentions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('raw_package_id', sa.UUID(), nullable=False),
    sa.Column('local_id', sa.String(length=128), nullable=False),
    sa.Column('original_title', sa.String(length=512), nullable=False),
    sa.Column('original_description', sa.String(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['raw_package_id'], ['raw_packages.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('raw_package_id', 'local_id')
    )
    op.create_table('event_resolution_contexts',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('temporal_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('participant_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('location_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['canonical_events.id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_table('ingestion_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('raw_package_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('pipeline_version', sa.String(length=32), nullable=False),
    sa.Column('report_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['raw_package_id'], ['raw_packages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('relationship_assertions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('relationship_id', sa.UUID(), nullable=False),
    sa.Column('assertion_kind', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('rationale', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['relationship_id'], ['graph_relationships.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('relationship_mentions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('raw_package_id', sa.UUID(), nullable=False),
    sa.Column('local_id', sa.String(length=128), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['raw_package_id'], ['raw_packages.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('raw_package_id', 'local_id')
    )
    op.create_table('source_mentions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('raw_package_id', sa.UUID(), nullable=False),
    sa.Column('local_id', sa.String(length=128), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['raw_package_id'], ['raw_packages.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('raw_package_id', 'local_id')
    )
    op.create_table('article_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('raw_package_id', sa.UUID(), nullable=False),
    sa.Column('source_mention_id', sa.UUID(), nullable=False),
    sa.Column('local_id', sa.String(length=128), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['raw_package_id'], ['raw_packages.id'], ),
    sa.ForeignKeyConstraint(['source_mention_id'], ['source_mentions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('raw_package_id', 'local_id')
    )
    op.create_table('claim_assertions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('claim_id', sa.UUID(), nullable=False),
    sa.Column('subject_type', sa.String(length=32), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('predicate', sa.String(length=128), nullable=False),
    sa.Column('object_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('temporal_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resolution_decisions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ingestion_id', sa.UUID(), nullable=False),
    sa.Column('incoming_type', sa.String(length=32), nullable=False),
    sa.Column('incoming_id', sa.String(length=128), nullable=False),
    sa.Column('outcome', sa.String(length=64), nullable=False),
    sa.Column('rationale', sa.String(), nullable=False),
    sa.Column('signals_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ingestion_id'], ['ingestion_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evidence_mentions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('raw_package_id', sa.UUID(), nullable=False),
    sa.Column('article_version_id', sa.UUID(), nullable=False),
    sa.Column('local_id', sa.String(length=128), nullable=False),
    sa.Column('excerpt', sa.String(), nullable=False),
    sa.Column('start_offset', sa.Integer(), nullable=False),
    sa.Column('end_offset', sa.Integer(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['article_version_id'], ['article_versions.id'], ),
    sa.ForeignKeyConstraint(['raw_package_id'], ['raw_packages.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('raw_package_id', 'local_id')
    )
    op.create_table('local_id_mappings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('raw_package_id', sa.UUID(), nullable=False),
    sa.Column('local_type', sa.String(length=32), nullable=False),
    sa.Column('local_id', sa.String(length=128), nullable=False),
    sa.Column('canonical_type', sa.String(length=32), nullable=False),
    sa.Column('canonical_id', sa.UUID(), nullable=False),
    sa.Column('decision_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['resolution_decisions.id'], ),
    sa.ForeignKeyConstraint(['raw_package_id'], ['raw_packages.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('raw_package_id', 'local_type', 'local_id')
    )
    op.create_table('provenance_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('graph_object_type', sa.String(length=32), nullable=False),
    sa.Column('graph_object_id', sa.UUID(), nullable=False),
    sa.Column('evidence_mention_id', sa.UUID(), nullable=True),
    sa.Column('raw_package_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['evidence_mention_id'], ['evidence_mentions.id'], ),
    sa.ForeignKeyConstraint(['raw_package_id'], ['raw_packages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('provenance_links')
    op.drop_table('local_id_mappings')
    op.drop_table('evidence_mentions')
    op.drop_table('resolution_decisions')
    op.drop_table('claim_assertions')
    op.drop_table('article_versions')
    op.drop_table('source_mentions')
    op.drop_table('relationship_mentions')
    op.drop_table('relationship_assertions')
    op.drop_table('ingestion_runs')
    op.drop_table('event_resolution_contexts')
    op.drop_table('event_mentions')
    op.drop_table('entity_mentions')
    op.drop_table('claims')
    op.drop_table('claim_mentions')
    op.drop_table('raw_packages')
    op.drop_table('graph_relationships')
    op.drop_table('canonical_events')
    op.drop_table('topics')
    op.drop_table('canonical_entities')
    # ### end Alembic commands ###
