"""add_rejected_packages

Revision ID: 77f47d76953c
Revises: a8a8205e2fe2
Create Date: 2026-07-25 18:37:07.731197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '77f47d76953c'
down_revision: Union[str, Sequence[str], None] = 'a8a8205e2fe2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rejected_packages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('package_id', sa.UUID(), nullable=True),
    sa.Column('schema_version', sa.String(length=16), nullable=True),
    sa.Column('topic_key', sa.String(length=128), nullable=True),
    sa.Column('payload_bytes', sa.LargeBinary(), nullable=False),
    sa.Column('payload_checksum', sa.String(length=64), nullable=False),
    sa.Column('report_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rejected_packages')
    # ### end Alembic commands ###
