"""add_confidence_assessments

Revision ID: a8a8205e2fe2
Revises: 712caca27763
Create Date: 2026-07-25 18:20:29.857712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8a8205e2fe2'
down_revision: Union[str, Sequence[str], None] = '712caca27763'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('confidence_assessments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('subject_type', sa.String(length=32), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('dimension', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('assessed_by', sa.String(length=64), nullable=False),
    sa.Column('method', sa.String(length=128), nullable=False),
    sa.Column('rationale', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('confidence_assessments')
    # ### end Alembic commands ###
